apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploment-test
    labels:
        name: demo-deployment
        app: test-app
        
spec:
    template:
            metadata: 
                name: test-pod-creation
                labels: 
                   app: demo-pod-creation
                   name: pod-creation-test 
            spec: 
                containers: 
                   - image: nginx
                     name: nginx
    replicas: 4
    selector:
        matchLabel:
            name: pod-creation-test