apiVersion: v1
kind: Service
metadata:
       name: service-deployment-test
       labels:
             name: service-test
             app: test
spec:
     type: NodePort
     ports: 
         targetPort: 80
         port: 80
         nodePort: 30008
     selector:
         app: demo-pod-creation